### ISSUE TITLE
Add `s3fs` and s3 credentials to repository

### ISSUE THREAD

**Issue by badgley** [carbonplan/forest-offsets-fires#6]
`forest-offsets-fires` was initially written to use i) prefect-cloud (prefect<2.0) and ii) google cloud storage. as we revamp the monitoring flow for 2023, we'd like to migrate away from GCS to s3. 

currently, the monitoring tasks run within a [customized docker image](https://github.com/carbonplan/forest-offsets-fires/blob/main/carbonplan_forest_offsets_fires/prefect/workflows/make_fire_tiles.py): `carbonplan/fire-monitor-prefect:2022.06.06`.

Running the monitoring flows requires adding `s3fs` to the image (see recent failed run: https://github.com/carbonplan/forest-offsets-fires/actions/runs/5008722147/jobs/8976893875). 

We also need to add s3 credentials to the [Action specification](https://github.com/carbonplan/forest-offsets-fires/blob/a01aedc937ddbbae9fa0790cb0a32cf2ca3ece6b/.github/workflows/nifc-perimeters.yaml#L24).

**Comment by maxrjones** [comment]
Addressed by https://github.com/carbonplan/forest-offsets-fires/pull/10 and https://github.com/carbonplan/forest-offsets-fires/pull/7
